color:
  brandColors:
    - '#FFFFFF'
    - '#E3E4DE'
    - '#ACACA2'
    - '#BEBEB4'
    - '#959D9F'
  brandStrength: 0.336349
  lightness: 1
  rhythmicContrast: 0.009618
  saturation: 0.181173
layout_spectrum: 0.208059
name: achingdiscontent
typography_spectrum: 0.438322
