name: achingdiscontent
favicon: null
layout_spectrum: 0.394737
typography_spectrum: 0.5
title: 'A c h i n g  D i s c o n t e n t '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B22234'
    - '#FFFFFF'
    - '#3C3B6E'
    - '#0E0E0E'
    - '#DC99A1'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
