analytics: {}
color:
  brandColors:
    - '#B22234'
    - '#FFFFFF'
    - '#3C3B6E'
    - '#0E0E0E'
    - '#DC99A1'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 0.505757
  saturation: 0.494243
cta: {}
layout_spectrum: 0.65248
name: achingdiscontent
opengraph: {}
purpose: []
title: 'A D '
typography_spectrum: 0.5
