name: achingdiscontent
favicon: null
layout_spectrum: 1
typography_spectrum: 0.438322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#E3E4DE'
    - '#ACACA2'
    - '#BEBEB4'
    - '#959D9F'
  brandStrength: 0.336349
  lightness: 1
  saturation: 0.181173
  rhythmicContrast: 1
purpose: []
